### ISSUE TITLE
使用    compile 'com.lzy.widget:imagepicker:0.4.6'  //指定版本最新版本 为啥点击预览报空

### ISSUE THREAD

**Issue by linyuchao** [jeasonlzy/ImagePicker#102]
Caused by: java.lang.NullPointerException
                                                                                      at com.lzy.imagepicker.adapter.ImagePageAdapter.getCount(ImagePageAdapter.java:71)
                                                                                      at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:532)
                                                                                      at com.lzy.imagepicker.ui.ImagePreviewBaseActivity.onCreate(ImagePreviewBaseActivity.java:89)
                                                                                      at com.lzy.imagepicker.ui.ImagePreviewDelActivity.onCreate(ImagePreviewDelActivity.java:29)
                                                                                      at android.app.Activity.performCreate(Activity.java:5231)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269) 
                                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by nanchen2251** [comment]
请注意一下你的启动相册以及点击预览的方法是否和demo中的WxDemoActivity保持一致。因为现在框架里面增加了新的东西，传值和之前有所更改。

**Comment by nanchen2251** [comment]
如果是在框架内预览，这个问题解决了，历史遗留问题，0.4.7中处理了。
