### ISSUE TITLE
ImageCropActivity OutOfMemoryError

### ISSUE THREAD

**Issue by SaltedFish999** [jeasonlzy/ImagePicker#113]
您好,  我在图片裁剪这里遇到了内存溢出的情况	
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:632)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:608)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:380)
	at com.lzy.imagepicker.ui.ImageCropActivity.onCreate(ImageCropActivity.java:75)

**Comment by ShengJunHu** [comment]
我三星手机拍照也发生了OOM异常的问题

**Comment by nanchen2251** [comment]
后面会解决。   请等待。

**Comment by nihaohebin** [comment]
他手机都会GC不会OOM（华为mete7 等），唯独这个毒三星A8 会OOM
ava.lang.OutOfMemoryError: Failed to allocate a 19907340 byte allocation with 5800072 free bytes and 5MB until OOM	
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)	
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)	
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:882)	
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:858)	
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:478)	
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:516)	

at com.lzy.imagepicker.util.BitmapUtil.rotateBitmapByDegree(BitmapUtil.java:103)	
at com.lzy.imagepicker.ui.ImageGridActivity.onActivityResult(ImageGridActivity.java:298)	

at android.app.Activity.dispatchActivityResult(Activity.java:7165)	
at android.app.ActivityThread.deliverResults(ActivityThread.java:5001)	
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5048)	
at android.app.ActivityThread.access$1600(ActivityThread.java:229)	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)	
at android.os.Handler.dispatchMessage(Handler.java:102)	
at android.os.Looper.loop(Looper.java:148)	
at android.app.ActivityThread.main(ActivityThread.java:7407)	
at java.lang.reflect.Method.invoke(Native Method)	
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1321)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)

**Comment by hundredays** [comment]
用Glide加载图片，不会有OOM

**Comment by nanchen2251** [comment]
可以看看。我一般都推荐用GlIde @SaltedFish999 @ShengJunHu

**Comment by SaltedFish999** [comment]
嗯... 我这边就是用的 Glide 图片加载框架，这个错误是百度统计捕捉到的 bug。具体指向的就是 ImageCropActivity

**Comment by nanchen2251** [comment]
好的，后面看看、

**Comment by ShengJunHu** [comment]
内存还需要进一步的优化！内存占用有点高，测试demo，内存占用就到达100M
