### ISSUE TITLE
你好，拍照时崩溃！麻烦看下！

### ISSUE THREAD

**Issue by youth5201314** [jeasonlzy/ImagePicker#114]
运行环境：buildToolsVersion "25.0.0"，手机是红米note1，Android 4.4.4，miui 8.2

java.lang.RuntimeException: Unable to resume activity {com.cdbqkj.cfs/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=null} to activity {com.cdbqkj.cfs/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.NullPointerException: file
                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254)
                             at android.app.ActivityThread.access$800(ActivityThread.java:141)
                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                             at android.os.Handler.dispatchMessage(Handler.java:102)
                             at android.os.Looper.loop(Looper.java:136)
                             at android.app.ActivityThread.main(ActivityThread.java:5113)
                             at java.lang.reflect.Method.invokeNative(Native Method)
                             at java.lang.reflect.Method.invoke(Method.java:515)
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                             at dalvik.system.NativeStart.main(Native Method)
                          Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=null} to activity {com.cdbqkj.cfs/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.NullPointerException: file
                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3367)
                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777)
                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819) 
                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254) 
                             at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                             at android.os.Looper.loop(Looper.java:136) 
                             at android.app.ActivityThread.main(ActivityThread.java:5113) 
                             at java.lang.reflect.Method.invokeNative(Native Method) 
                             at java.lang.reflect.Method.invoke(Method.java:515) 
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                             at dalvik.system.NativeStart.main(Native Method) 
                          Caused by: java.lang.NullPointerException: file
                             at android.net.Uri.fromFile(Uri.java:444)
                             at com.lzy.imagepicker.ImagePicker.galleryAddPic(ImagePicker.java:294)
                             at com.lzy.imagepicker.ui.ImageGridActivity.onActivityResult(ImageGridActivity.java:290)
                             at android.app.Activity.dispatchActivityResult(Activity.java:5434)
                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
                             at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777) 
                             at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819) 
                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254) 
                             at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                             at android.os.Looper.loop(Looper.java:136) 
                             at android.app.ActivityThread.main(ActivityThread.java:5113) 
                             at java.lang.reflect.Method.invokeNative(Native Method) 
                             at java.lang.reflect.Method.invoke(Method.java:515) 
                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                             at dalvik.system.NativeStart.main(Native Method)

**Comment by youth5201314** [comment]
源码调试时： Caused by: java.lang.NullPointerException: file
                             at android.net.Uri.fromFile(Uri.java:444)
                             at com.lzy.imagepicker.ImagePicker.galleryAddPic(ImagePicker.java:294)
                             at com.lzy.imagepicker.ui.ImageGridActivity.onActivityResult(ImageGridActivity.java:290)

**Comment by nanchen2251** [comment]
使用版本是最新的吗？

**Comment by q4401140** [comment]
是因为手机回收机制的原因，去拍照以后你的ImageGridActivity被销毁了，所以Uri.fromFile 代码这一段这个参数为null，你可以重写onSaveInstanceState方法，把这个指定路径的文件保存好，然后恢复activity的时候再取出来
