### ISSUE TITLE
红米手机拍照返回崩溃

### ISSUE THREAD

**Issue by pardonhan** [jeasonlzy/ImagePicker#124]
红米 note4 Android 6.0 api23 拍照确认后崩溃；
我调试的时候没有报，但是我的app直接崩溃了，这是运行在手机上的时候报的错误 request=1001, result=-1, data=null  NullPointerException 
```
java.lang.RuntimeException: Unable to resume activity 
{com.xx.xx/com.lzy.imagepicker.ui.ImageGridActivity}:
 java.lang.RuntimeException: Failure delivering result ResultInfo
{who=null, request=1001, result=-1, data=null} to activity 
{com.xx.xx/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.NullPointerException: file
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3273)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3304)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2618)
	at android.app.ActivityThread.access$900(ActivityThread.java:180)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=null} to activity {com.xx.xx/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.NullPointerException: file
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3888)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3255)
	... 10 more
Caused by: java.lang.NullPointerException: file
	at android.net.Uri.fromFile(Uri.java:452)
	at com.lzy.imagepicker.ImagePicker.galleryAddPic(ImagePicker.java:294)
	at com.lzy.imagepicker.ui.ImageGridActivity.onActivityResult(ImageGridActivity.java:290)
	at android.app.Activity.dispatchActivityResult(Activity.java:6479)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3884)
	... 11 more
``

**Comment by nanchen2251** [comment]
你好，是本项目的demo报错吗？

**Comment by q4401140** [comment]
你这个问题，我解决了，是因为手机回收机制的原因，去拍照以后你的ImageGridActivity被销毁了，所以Uri.fromFile 代码这一段这个参数为null，你可以重写onSaveInstanceState方法，把这个指定路径的文件保存好，然后恢复activity的时候再取出来
