### ISSUE TITLE
相册页面内存溢出

### ISSUE THREAD

**Issue by ganshenml** [jeasonlzy/ImagePicker#129]
进入相册页面后内存占用猛增，退出页面后也没有释放；
之前看到有忍去年反馈过，还望@jeasonlzy  早点解决啊，衷心感谢。

`Request threw uncaught throwable
                                                                  java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
                                                                      at java.util.concurrent.FutureTask.report(FutureTask.java:93)
                                                                      at java.util.concurrent.FutureTask.get(FutureTask.java:163)
                                                                      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
                                                                   Caused by: java.lang.OutOfMemoryError
                                                                      at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                      at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:632)
                                                                      at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:608)
                                                                      at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
                                                                      at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
                                                                      at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
                                                                      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
                                                                      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
                                                                      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
                                                                      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:24)
                                                                      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:14)
                                                                      at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:39)
                                                                      at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:17)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.loadFromCache(DecodeJob.java:222)
                                                                      at com.bumptech.glide.load.engine.DecodeJob.decodeResultFromCache(DecodeJob.java:85)
                                                                      at com.bumptech.glide.load.engine.EngineRunnable.decodeFromCache(EngineRunnable.java:108)
                                                                      at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:99)
                                                                      at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) 
                                                                      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118) `

**Comment by ganshenml** [comment]
依赖了最新版，结果发现以上内存溢出问题还是存在。@nanchen2251

**Comment by ganshenml** [comment]
最终还是发现了原因，在图片加载器的类中，我是使用的Glide，而且里面加了这样一句：
  //  .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL) 这一句千万不能要，不然内存占用过多，而且，退出界面了始终释放不了！

**Comment by nanchen2251** [comment]
那挺好的。
