### ISSUE TITLE
进入多选时报错如下：

### ISSUE THREAD

**Issue by micrologic** [jeasonlzy/ImagePicker#136]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lzy.imagepicker.ui.ImagePreviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3320)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7326)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
                                                                      at com.lzy.imagepicker.ui.ImagePreviewBaseActivity.onCreate(ImagePreviewBaseActivity.java:67)
                                                                      at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:40)
                                                                      at android.app.Activity.performCreate(Activity.java:6904)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3267)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416) 
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7326) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by nanchen2251** [comment]
你好，请问是demo直接报错吗

**Comment by micrologic** [comment]
不是demo,是集成到项目里面，

**Comment by nanchen2251** [comment]
对洛，所以我建议你们用开源框架，先下载demo来查看一下怎么用吧。你这应该是传递的参数没传正确。才会导致这样的。

**Comment by nanchen2251** [comment]
一般遇到问题，我建议的是先看demo有没有问题，如果demo也有问题，才会是机型适配等的问题。如果后面你解决了。记得自己关闭issues.
