### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by z8806c** [jeasonlzy/ImagePicker#14]
time-->2016-05-26 15:37
sdk-->17
device-->bbk89_cmcc_jb2
info-->java.lang.NullPointerException
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:529)
    at android.view.View.measure(View.java:15624)
    at com.lzy.imagepicker.adapter.ImageFolderAdapter.getItemViewHeight(ImageFolderAdapter.java:71)
    at com.lzy.imagepicker.ui.ImageGridActivity.createPopupFolderList(ImageGridActivity.java:146)
    at com.lzy.imagepicker.ui.ImageGridActivity.onClick(ImageGridActivity.java:112)
    at android.view.View.performClick(View.java:4224)
    at android.view.View$PerformClick.run(View.java:17461)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5344)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by jeasonlzy0216** [comment]
0.2.4 以后支持横竖屏切换。。
