### ISSUE TITLE
小米6.0系统打开相机提示三次获取相机权限，然后就奔溃了！！！

### ISSUE THREAD

**Issue by 897902334** [jeasonlzy/ImagePicker#143]
小米6.0系统打开相机提示三次获取相机权限，没来得及点击允许 然后就奔溃了！！！，报的是数组越界了！！
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lzy.imagepickerdemo/com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                             at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                          Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                             at com.lzy.imagepicker.ui.ImageGridActivity.onRequestPermissionsResult(ImageGridActivity.java:132)
                                                                             at android.app.Activity.requestPermissions(Activity.java:3872)
                                                                             at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                                             at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                                             at com.lzy.imagepicker.ui.ImageGridActivity.onCreate(ImageGridActivity.java:123)
                                                                             at android.app.Activity.performCreate(Activity.java:6303)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                             at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5524) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) `

**Comment by nanchen2251** [comment]
这个应该是小米手机回去的时候Activity被回收导致，后期修复。

**Comment by 897902334** [comment]
恩，感谢回复，  我现在处理的方法就是提前获取一下相机权限，获取成功后。  但是！！  我点击拍照  他还是提示我获取相机权限，  我觉得你这块是不是应该判断当前应用是否有某个权限，如果没有再获取呢？  我是这么想的···   也没有仔细研究你的代码！     愿尽快修复小问题！  感谢。

**Comment by nanchen2251** [comment]
你应该是不需要去获取相机权限的。

**Comment by 897902334** [comment]
恩。
我不提前获取权限的话，  我点击打开相机，他就提示我三次获取相机权限的Dialog，我点了一个另外一个弹出了  然后程序就奔溃了 ····就上面的那些报错日志(数组越界！)   所以我就想了个提前获取权限的方法·············

**Comment by coder-xiaoshuai** [comment]
现在通过依赖方式 导入的库是最新代码吗

**Comment by nanchen2251** [comment]
是的

**Comment by coder-xiaoshuai** [comment]
嗯嗯  我直接依赖的  发现直接预览图片选中图片  返回上个页面没有选中  但是demo没有这个问题

**Comment by nanchen2251** [comment]
额，那可能是最新的还没上传，后面会上传的，不能更新太快，现在都是小Bug。
