### ISSUE TITLE
NullPointerException Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by yezishu** [jeasonlzy/ImagePicker#150]
追踪了一下 源代码应该是CropImageView .getDrawable  getBitmap获取到的为null

` Bitmap srcBitmap = ((BitmapDrawable) getDrawable()).getBitmap();
        srcBitmap = rotate(srcBitmap, sumRotateLevel * 90);  //最好用level，因为角度可能不是90的整数
        return makeCropBitmap(srcBitmap, mFocusRect, getImageMatrixRect(), expectWidth, exceptHeight, isSaveRectangle);` 

机型华为荣耀7 Android, HONOR/PLK-AL10
系统版本 android 6.0    EMUI系统4.0.3 
报错的log信息
`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
at com.lzy.imagepicker.view.CropImageView.makeCropBitmap(CropImageView.java:489)
at com.lzy.imagepicker.view.CropImageView.getCropBitmap(CropImageView.java:444)
at com.lzy.imagepicker.view.CropImageView.saveBitmapToFile(CropImageView.java:532)
at com.lzy.imagepicker.ui.ImageCropActivity.onClick(ImageCropActivity.java:104)
at android.view.View.performClick(View.java:5264)
at android.view.View$PerformClick.run(View.java:21297)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5621)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

**Comment by nanchen2251** [comment]
请在新版本测试一下

**Comment by yezishu** [comment]
有个点忘了提了，就是这个触发这个bug的时候，我调用的是不需要裁剪的拍照。
然后出错跳转到了裁剪的界面才报错，具体为什么以及怎么触发跳转到裁剪界面原因不明。

**Comment by nanchen2251** [comment]
不需要裁剪的拍照？你在哪个页面弄的？

**Comment by yezishu** [comment]
`...`
` mImagePicker.setCrop(false); `
`...`
 `intent.putExtra(ImageGridActivity.EXTRAS_TAKE_PICKERS,true);`

跳转的主要参数，直接跳转拍照界面，然后不开启裁剪功能。

**Comment by nanchen2251** [comment]
你这是在第一个页面呀。暂时我只维护了WxDemoActivity的
你看看第二个仿微信是否有问题。
