### ISSUE TITLE
进入图片选择，点击图片崩溃

### ISSUE THREAD

**Issue by 1226362423** [jeasonlzy/ImagePicker#159]

**Comment by 1226362423** [comment]
java.lang.NoClassDefFoundError: uk.co.senab.photoview.PhotoViewAttacher
                                                                        at uk.co.senab.photoview.PhotoView.init(PhotoView.java:54)
                                                                        at uk.co.senab.photoview.PhotoView.<init>(PhotoView.java:49)
                                                                        at uk.co.senab.photoview.PhotoView.<init>(PhotoView.java:43)
                                                                        at uk.co.senab.photoview.PhotoView.<init>(PhotoView.java:39)
                                                                        at com.lzy.imagepicker.adapter.ImagePageAdapter.instantiateItem(ImagePageAdapter.java:56)
                                                                        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1182)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:15523)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)

**Comment by androidshu** [comment]
是否为应用太大，方法数超出限制了呢？

**Comment by SkyHots** [comment]
解决了吗  我也遇到了这个问题

**Comment by SkyHots** [comment]
如果是打成aar包之后或者直接引用博主的library，出现此问题的原因是工程缺少一个依赖库（因为博主的demo中添加过下面这个库）  
请 添加compile 'com.github.chrisbanes.photoview:library:1.2.4'库到你的项目的依赖下面就ok了    我也是刚遇到了这个问题。
