### ISSUE TITLE
版本号：0.5.5 手机：MI  5   系统：7.0

### ISSUE THREAD

**Issue by sungentim** [jeasonlzy/ImagePicker#164]
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/IMG_20170519_110438.jpg
	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
	at com.lzy.imagepicker.ImagePicker.takePicture(ImagePicker.java:280)
	at com.lzy.imagepicker.adapter.ImageRecyclerAdapter$CameraViewHolder$1.onClick(ImageRecyclerAdapter.java:199)
	at android.view.View.performClick(View.java:5611)
	at android.view.View$PerformClick.run(View.java:22276)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6114)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by sungentim** [comment]
这个问题我也出现了和诺次

**Comment by sungentim** [comment]
这个问题我也出现了很多次

**Comment by nanchen2251** [comment]
- - 老铁，你的问题收到了，但鉴于近期活太多了，暂时管不了呀。你们也可以帮着查找问题呀。

**Comment by sungentim** [comment]
<root-path path="" name="camera_photos" />
http://www.jianshu.com/p/121bbb07cb07
