### ISSUE TITLE
ImagePicker 在选择图片界面 按了拍照按钮，APP 会崩溃

### ISSUE THREAD

**Issue by chenyusheng** [jeasonlzy/ImagePicker#169]
项目 SDK 25
手机 一加3 Android 7.1版本
报错如下：
E/CrashReport: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/DCIM/camera/IMG_20170601_103123.jpg
                                                    at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
                                                    at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
                                                    at com.lzy.imagepicker.ImagePicker.takePicture(ImagePicker.java:280)
                                                    at com.lzy.imagepicker.adapter.ImageRecyclerAdapter$CameraViewHolder$1.onClick(ImageRecyclerAdapter.java:199)
                                                    at android.view.View.performClick(View.java:5669)
                                                    at android.view.View$PerformClick.run(View.java:22549)
                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.app.ActivityThread.main(ActivityThread.java:6322)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by dyfan** [comment]
同问,我也是这个问题,关键demo还没问题

**Comment by nanchen2251** [comment]
先查看demo是否存在问题，目前这个问题有点奇葩。因为我们公司项目也用的这个框架，但没有出现过类似情况。

**Comment by chenyusheng** [comment]
看报错是找不到路径：/storage/emulated/0/DCIM/camera/IMG_20170601_103123.jpg
这个是拍照之后图片保存的位置？
但是都还没有开始拍就跪了

**Comment by Tungtive** [comment]
请问这个bug解决了吗？？
