### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by moon2009** [jeasonlzy/ImagePicker#172]
Fatal Exception: java.lang.NullPointerException
       at com.lzy.imagepicker.view.CropImageView.makeCropBitmap(CropImageView.java:511)
       at com.lzy.imagepicker.view.CropImageView.getCropBitmap(CropImageView.java:466)
       at com.lzy.imagepicker.view.CropImageView.saveBitmapToFile(CropImageView.java:554)
       at com.lzy.imagepicker.ui.ImageCropActivity.onClick(ImageCropActivity.java:104)
后台统计这个地方有错误

**Comment by nanchen2251** [comment]
估计是图片被干掉了。居然也不清楚什么原因

**Comment by yezishu** [comment]
我也是这个问题，目前跟踪的情况是，我原本是调用拍照但是不裁剪，但是出问题跳到裁剪界面所以点了裁剪就报空指针

**Comment by nanchen2251** [comment]
后期看看，可能是裁剪某个步骤把图片干没了。
