### ISSUE TITLE
红米Note 1s  拍照崩溃

### ISSUE THREAD

**Issue by MrPsw** [jeasonlzy/ImagePicker#179]
java.lang.NullPointerException
	at com.lzy.imagepicker.view.CropImageView.saveOutput(CropImageView.java:571)
	at com.lzy.imagepicker.view.CropImageView.access$000(CropImageView.java:50)
	at com.lzy.imagepicker.view.CropImageView$1.run(CropImageView.java:547)

**Comment by nanchen2251** [comment]
已收到，后期修复。

**Comment by wangcheng24** [comment]
同样 红米 note1s

**Comment by Joshua-Chang** [comment]
同样vivo9p
