### ISSUE TITLE
努比亚手机zmin11崩溃

### ISSUE THREAD

**Issue by yanchunlan** [jeasonlzy/ImagePicker#184]
坑爹啊。竟然不维护了，那么多bug
异常信息：
java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                   at java.io.File.fixSlashes(File.java:185)
                                                   at java.io.File.<init>(File.java:134)
                                                   at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:102)

跟踪到的位置是：
  //根据父路径分类存放图片
                File imageFile = new File(imagePath);

**Comment by hlla** [comment]
慎言,大佬又不欠咱们的,别寒了大佬的心
