### ISSUE TITLE
7.0部分机型偶发空指针

### ISSUE THREAD

**Issue by VDshixiaoming** [jeasonlzy/ImagePicker#185]
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
1 android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
2 android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
3 android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
4 com.xxx.f.a(ImagePicker.java:320)
5 com.xxx.a.c.onClick(ImageGridAdapter.java:110)

空指针定位在代码ImagePicker
/**
* 7.0 调用系统相机拍照不再允许使用Uri方式，应该替换为FileProvider
* 并且这样可以解决MIUI系统上拍照返回size为0的情况
*/
uri = FileProvider.getUriForFile(activity, activity.getPackageName() + ".provider", takeImageFile);

**Comment by VDshixiaoming** [comment]
华为P9，6.0调用相机拍照时必现
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                      at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                      at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                      at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                      at com.vdian.imagechooser.imageChooser.ImagePicker.takePicture(ImagePicker.java:320)
                      at com.vdian.imagechooser.imageChooser.adapter.ImageGridAdapter$1.onClick(ImageGridAdapter.java:110)`

**Comment by VDshixiaoming** [comment]
暂时用try-catch处理了下：
`if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) {
                    try {
                        takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(takeImageFile));
                    } catch (Exception e) {
                        /**
                         * 7.0 调用系统相机拍照不再允许使用Uri方式，应该替换为FileProvider
                         * 并且这样可以解决MIUI系统上拍照返回size为0的情况
                         */
                        Uri uri = FileProvider.getUriForFile(activity, activity.getPackageName() + ".provider", takeImageFile);
                        //加入uri权限 要不三星手机不能拍照
                        List<ResolveInfo> resInfoList = activity.getPackageManager().queryIntentActivities
                                (takePictureIntent, PackageManager.MATCH_DEFAULT_ONLY);
                        for (ResolveInfo resolveInfo : resInfoList) {
                            String packageName = resolveInfo.activityInfo.packageName;
                            activity.grantUriPermission(packageName, uri, Intent
                                    .FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
                        }
                        takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, uri);
                    }

                } else {
                    takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(takeImageFile));
                }`
