### ISSUE TITLE
三星SM-E7000崩溃。安卓4.4.4（手机貌似刷过机）

### ISSUE THREAD

**Issue by Ashion-AS** [jeasonlzy/ImagePicker#189]
07-27 18:22:10.056 26651-26651/com.lzy.imagepickerdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.lzy.imagepickerdemo, PID: 26651
                                                                         java.lang.NullPointerException
                                                                             at com.lzy.imagepicker.adapter.ImageRecyclerAdapter$ImageViewHolder.bind(ImageRecyclerAdapter.java:176)
                                                                             at com.lzy.imagepicker.adapter.ImageRecyclerAdapter.onBindViewHolder(ImageRecyclerAdapter.java:95)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                             at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                             at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                             at android.view.View.layout(View.java:15886)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:4932)
                                                                             at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2419)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2132)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1311)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6711)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:613)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:583)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
                                                                         	at

**Comment by Ashion-AS** [comment]
发现是手机自身问题，和项目不关，故关闭。
