### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ganshenml** [jeasonlzy/ImagePicker#190]
`java.lang.IndexOutOfBoundsException: Invalid index 7, size is 4
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.lzy.imagepicker.ui.ImageGridActivity.a(ImageGridActivity.java:273)
	at com.lzy.imagepicker.a.d$b$1.onClick(ImageRecyclerAdapter.java:145)
	at android.view.View.performClick(View.java:5702)
	at android.view.View$PerformClick.run(View.java:22546)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by SkyHots** [comment]
@ganshenml  解决了吗兄弟

**Comment by ganshenml** [comment]
@blankfu 忘了o(╯□╰)o
