### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference at com.lzy.imagepicker.ui.ImagePreviewBaseActivity.onCreate(ImagePreviewBaseActivity.java:53) at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:40) at android.app.Activity.performCreate(Activity.java:6303)

### ISSUE THREAD

**Issue by tracy891110** [jeasonlzy/ImagePicker#218]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
at com.lzy.imagepicker.ui.ImagePreviewBaseActivity.onCreate(ImagePreviewBaseActivity.java:53)
at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:40)
at android.app.Activity.performCreate(Activity.java:6303)

**Comment by zizhz2018** [comment]
楼上的问题解决了吗我与到的问题貌似跟你一样呢。。。。。。。。。。。。。。

**Comment by liwk** [comment]
我也碰到了这个问题，有没有解决？

**Comment by ZhenmingMa** [comment]
请确认项目中layout文件是否于jar包中的有冲突。没有正确的加载到这个layout文件导致的

**Comment by xuwei7746521** [comment]
真是坑死人的库
