### ISSUE TITLE
预览图片就报错，不知道为什么

### ISSUE THREAD

**Issue by minmei** [jeasonlzy/ImagePicker#22]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
                                                                        at com.lzy.imagepicker.ui.ImagePreviewBaseActivity.onCreate(ImagePreviewBaseActivity.java:53)
                                                                        at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:40)
                                                                        at android.app.Activity.performCreate(Activity.java:6303)

**Comment by ZhenmingMa** [comment]
请确认项目中layout文件是否于jar包中的有冲突。没有正确的加载到这个layout文件导致的
