### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.lzy.imagepicker.ImagePickerProvider: java.lang.ClassNotFoundException: Didn't find class "com.lzy.imagepicker.ImagePickerProvider" on path: DexPathList[[zip file "/data/app/com.wiscess.reading-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.wiscess.reading-2, /vendor/lib, /system/lib]]

### ISSUE THREAD

**Issue by fenwind** [jeasonlzy/ImagePicker#220]
11-21 14:15:24.454 28511-28511/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.RuntimeException: Unable to get provider com.lzy.imagepicker.ImagePickerProvider: java.lang.ClassNotFoundException: Didn't find class "com.lzy.imagepicker.ImagePickerProvider" on path: DexPathList[[zip file "/data/app/com.wiscess.reading-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.wiscess.reading-2, /vendor/lib, /system/lib]]
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:4957)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4560)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4500)
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:144)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5178)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lzy.imagepicker.ImagePickerProvider" on path: DexPathList[[zip file "/data/app/com.wiscess.reading-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.wiscess.reading-2, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)

**Comment by yanlianhanlin** [comment]
我也碰到这个问题了，你解决了码

**Comment by scuthua** [comment]
我也遇到了这个问题。ImagePickerProvider找不到，后来发现是我自己的MultiDex初始化的位置不对。我在application的onCreate中执行的MultiDex.install，应该在Application的attachBaseContext中执行的。
希望对你有用。

**Comment by weileng11** [comment]
MultiDex.install应该在Application的attachBaseContext中执行解决了我的问题，大家可以这样试试。

**Comment by df13954** [comment]
直接继承也可以的，具体看https://developer.android.com/studio/build/multidex.html?hl=zh-CN
Application的attachBaseContext是自定义不继承的情况这样。
问题出现是因为多dex情况。
