### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by Moomesy** [jeasonlzy/ImagePicker#227]
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
	at java.util.ArrayList.get(ArrayList.java:313)
	at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:130)
	at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:27)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5743)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1077)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:843)

**Comment by PaulLuv** [comment]
兄弟，解决了吗？
