### ISSUE TITLE
手机拍照后点确定崩溃，日志如下

### ISSUE THREAD

**Issue by GeniusJerry** [jeasonlzy/ImagePicker#262]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qdcadc.monitor/com.lzy.imagepicker.ui.ImageCropActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.lzy.imagepicker.ui.ImageCropActivity.onCreate(ImageCropActivity.java:62)
	at android.app.Activity.performCreate(Activity.java:6664)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	... 9 more

**Comment by vyve** [comment]
请问问题解决了吗？

**Comment by GeniusJerry** [comment]
还没有呢
