### ISSUE TITLE
ImagePicker出现的几个bug

### ISSUE THREAD

**Issue by ecliujianbo** [jeasonlzy/ImagePicker#288]
1，java.lang.IndexOutOfBoundsException

型号：小米 MI NOTE 3
版本：Android 8.1.0,level 27

详情：

Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
 AndroidRuntime: at java.util.ArrayList.get(ArrayList.java:437)
 AndroidRuntime: at com.lzy.imagepicker.ui.ImageCropActivity.onCreate(ImageCropActivity.java:77)

------------------------------
2， java.lang.IndexOutOfBoundsException

型号：VIVO V1813T
版本：Android 8.1.0,level 27

详情：
java.util.ArrayList.get(ArrayList.java:437)
 com.lzy.imagepicker.ui.ImageGridActivity.onImageItemClick(ImageGridActivity.java:282)
 com.lzy.imagepicker.adapter.ImageRecyclerAdapter$ImageViewHolder$1.onClick(ImageRecyclerAdapter.java:148)

----------------------------------------
3，java.lang.IndexOutOfBoundsException

型号：VIVO Y79A
版本：Android 7.1.2,level 25

详情
java.util.ArrayList.get(ArrayList.java:411)
 com.lzy.imagepicker.ImagePicker.getCurrentImageFolderItems(ImagePicker.java:219)
 com.lzy.imagepicker.ui.ImageGridActivity.onImageItemClick(ImageGridActivity.java:282)
 com.lzy.imagepicker.adapter.ImageRecyclerAdapter$ImageViewHolder$1.onClick(ImageRecyclerAdapter.java:148)

-----------------------------------------
4， java.lang.IndexOutOfBoundsException

型号：VIVO X9
版本：Android 6.0.1,level 23

详情：

Caused by:
 java.lang.IndexOutOfBoundsException:Invalid index 0, size is 0
 java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
 java.util.ArrayList.get(ArrayList.java:308)
 com.lzy.imagepicker.ui.ImageCropActivity.onCreate(ImageCropActivity.java:77)

------------------------------------------------
5，java.lang.IllegalArgumentException(异常类型可能不准确)

型号：VIVO X9；摩托罗拉 XT1635 03
版本：Android 6.0.1,level 23；Android 7.1.1,level 25

详情：
CropImageView中的getCropBitmap()方法
 Bitmap srcBitmap = ((BitmapDrawable) getDrawable()).getBitmap();这里获取的srcBitmap=null

**Comment by beijing-java** [comment]
我不关注问题，而我想了解下您是通过何种方式来进行的测试，这么详细，膜拜。 @ecliujianbo

**Comment by lizhangqu** [comment]
@ecliujianbo support版本问题，>=27.1.0就会有问题，Loader行为变更

**Comment by 4159141** [comment]
拷贝源码中的ImagePicker作为项目的module是否可以解决数组越界的问题呢？
