### ISSUE TITLE
设置可裁剪图片后，选择图片，进入裁剪页面，再直接返回会闪退

### ISSUE THREAD

**Issue by RockRoll666** [jeasonlzy/ImagePicker#304]
报错代码及原因如下
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:130)
at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:27)

**Comment by luck8528t** [comment]
一样问题,没人解决吗
