### ISSUE TITLE
三星G9008拍照奔溃,报file空指针.

### ISSUE THREAD

**Issue by wanghuitaolove** [jeasonlzy/ImagePicker#48]

**Comment by seefcn** [comment]
红米1S也报异常
Caused by: java.lang.NullPointerException: file
	at android.net.Uri.fromFile(Uri.java:444)
	at com.lzy.imagepicker.ImagePicker.galleryAddPic(ImagePicker.java:269)
	at com.lzy.imagepicker.ui.ImageGridActivity.onActivityResult(ImageGridActivity.java:248)

**Comment by seefcn** [comment]
看到了一篇文章http://www.piaoyi.org/mobile-app/Android-MIUI-BUG-photo-activity.html
另外，为了防止在调用相机的时候，当前activity被系统kill（比如内存不够时，系统会自动销毁非可见的处于onPause或onStop状态的activity），我们需要 覆写 onSaveInstanceState方法，保存当前activity的状态变量值。
然后在 onCreate(Bundle savedInstanceState) 方法里，判断savedInstanceState是否为null，不是null则读取上次保存的临时变量值。
