### ISSUE TITLE
Android7.0 打开照相机会崩溃

### ISSUE THREAD

**Issue by HYVincent** [jeasonlzy/ImagePicker#63]
Process: com.school.rainbow, PID: 526
                                                                android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/camera/IMG_20170110_201413.jpg exposed beyond app through ClipData.Item.getUri()
                                                                    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1816)
                                                                    at android.net.Uri.checkFileUriExposed(Uri.java:2350)
                                                                    at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                                    at android.content.Intent.prepareToLeaveProcess(Intent.java:9052)
                                                                    at android.content.Intent.prepareToLeaveProcess(Intent.java:9037)
                                                                    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1530)
                                                                    at android.app.Activity.startActivityForResult(Activity.java:4391)
                                                                    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                    at android.app.Activity.startActivityForResult(Activity.java:4335)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                    at com.lzy.imagepicker.ImagePicker.takePicture(ImagePicker.java:255)
                                                                    at com.lzy.imagepicker.adapter.ImageGridAdapter$1.onClick(ImageGridAdapter.java:107)
                                                                    at android.view.View.performClick(View.java:5646)
                                                                    at android.view.View$PerformClick.run(View.java:22450)
                                                                    at android.os.Handler.handleCallback(Handler.java:755)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:156)

**Comment by sujianqingfeng** [comment]
现在还没有适配

**Comment by CNCFOX** [comment]
解决代码已经提交给，等待合并，如果急需请到Pull Request 中查找

**Comment by nanchen2251** [comment]
该问题已经解决。
