### ISSUE TITLE
预览空指针

### ISSUE THREAD

**Issue by HYVincent** [jeasonlzy/ImagePicker#81]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vincent.hss/com.lzy.imagepicker.ui.ImagePreviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                                     at com.lzy.imagepicker.DataHolder.retrieve(DataHolder.java:40)
                                                                     at com.lzy.imagepicker.ui.ImagePreviewBaseActivity.onCreate(ImagePreviewBaseActivity.java:46)
                                                                     at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:40)
                                                                     at android.app.Activity.performCreate(Activity.java:6910)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:156) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6524) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by HYVincent** [comment]
//图片预览空指针
    public Object retrieve(String id) {
        WeakReference<Object> objectWeakReference = data.get(id);
        return objectWeakReference.get();
    }

**Comment by HYVincent** [comment]
com.lzy.imagepicker.DataHolder
