### ISSUE TITLE
在android7.0以后的手机上，点击拍照按钮崩溃

### ISSUE THREAD

**Issue by moonljt521** [jeasonlzy/ImagePicker#88]
在android7.0以后的手机上，点击拍照按钮崩溃：
android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/camera/IMG_20170316_122732.jpg exposed beyond app through ClipData.Item.getUri()

希望您抽时间作个适配

**Comment by nanchen2251** [comment]
7.0的崩溃问题，我已经可以解决，近期我会贡献自己的代码，到时候就看廖大神merge不了。

**Comment by moonljt521** [comment]
多谢

**Comment by nanchen2251** [comment]
作者已经merge了。你测试一下，应该7.0没问题了。

**Comment by moonljt521** [comment]
效率好高。
我看作者这个项目标注不再维护了，而且compile的版本号没有变化，是代表我只能依赖源码了嘛

**Comment by nanchen2251** [comment]
没事儿，廖哥最近很忙，在维护OkGo，我可以帮着维护，换一种依赖方式。我去问问廖哥，如果可以我来做维护处理。可以关注。

**Comment by moonljt521** [comment]
😊

**Comment by moonljt521** [comment]
我测了一下，7.1手机上拍照返回照片正常了， 在我的一款三星note2 4.3手机上拍照返回照片时崩溃
ATAL EXCEPTION: main
                                                   java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{43896938 27627:com.sec.android.app.camera/u0a10072} (pid=27627, uid=10072) that is not exported from uid 10170
                                                       at android.os.Parcel.readException(Parcel.java:1431)
                                                       at android.os.Parcel.readException(Parcel.java:1385)
                                                       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2956)
                                                       at android.app.ActivityThread.acquireProvider(ActivityThread.java:4859)
                                                       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2551)
                                                       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1152)
                                                       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:667)
                                                       at android.content.ContentResolver.openOutputStream(ContentResolver.java:540)
                                                       at android.content.ContentResolver.openOutputStream(ContentResolver.java:516)
                                                       at com.sec.android.app.camera.Camera$LastContentUriCallback.onCompleted(Camera.java:5915)
                                                       at com.sec.android.app.camera.Camera.onLaunchGallery(Camera.java:5797)
                                                       at com.sec.android.app.camera.Camera.onImageStoringCompleted(Camera.java:5165)
                                                       at com.sec.android.app.camera.CameraEngine.imageStoringCompleted(CameraEngine.java:2326)
                                                       at com.sec.android.app.camera.CeStateInitialized.handleMessage(CeStateInitialized.java:47)
                                                       at com.sec.android.app.camera.CameraEngine$StateMessageHandler.handleMessage(CameraEngine.java:253)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5528)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by nanchen2251** [comment]
我这里没有那么多测试机呢？或许你可以下载源码帮忙更改一下，而且现在我有些忙。。

**Comment by nanchen2251** [comment]
这个情况已经知道了。你直接clean一下就好了。
